
name: Library workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Node 
      run: npm install
 
    - name: Install Playwright
      run:   npx playwright install 
    - name: Run Tests
      run: |
        npm start &   # Start the server in the background
        sleep 5       # Give it some time to start
        while ! curl -s http://localhost:3000; do
            echo "Waiting for server to start..."
            sleep 1
        done
        npm test      # Run your tests
      

  
    
  deploy_server:
      needs: build
      runs-on: ubuntu-latest
      steps:
    
        - uses: actions/checkout@v4
        - name: Deploy to Render
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID_SERVER }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 
  
  deploy_static:
      needs: deploy_server
      runs-on: ubuntu-latest
      steps:
    
        - uses: actions/checkout@v4
        - name: Deploy to Render
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true